make schedule section
citrushack/cutiehack2022 pull request #35
Opened 2022-08-01 05:10 UTC by nibchao

- I'm not sure how to make the columns (Events/Workshops/Activities) as wide as they appear on the CutieHack page. 
- I don't know how to make the descriptor text for each schedule item fit on a single line rather than continuing onto another line. 
- Also I am not sure which <h#> to use and whether I should be using <p> instead of <div> for some of the elements.

2022-08-01 05:29 UTC, andreidimaano commented
Can you upload a screenshot of what it looks like

2022-08-01 05:33 UTC, andreidimaano commented on pages/Schedules.tsx
> +        <h3>Schedule is in PST (Pacific Standard Time)</h3>
use <p>

2022-08-01 05:33 UTC, andreidimaano commented on pages/Schedules.tsx
> +        <h2>Saturday, April 2</h2>
use `<p>` for this one too

2022-08-01 05:34 UTC, andreidimaano commented on pages/Schedules.tsx
> +        <div className="flex flex-row gap-12 px-12 my-6">
make sure your divs have class names that describe what the div does
ex: `schedule-wrapper`

2022-08-01 05:47 UTC, andreidimaano commented on pages/Schedules.tsx
> +              <div className="flex flex-col w-full text-left font-medium">
Refactor into a Map and have a separate React.component that renders each column
example:

Code Pointers: 

- [keys of a map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)
- [refactoring using a map](https://github.com/andreidimaano/portfoliov2/blob/main/scripts/casestudy.js)
- [rendering using a map](https://contactmentor.com/render-array-map-react-js/)

```
In a utils file:
const Schedule = new Map ([
    [ 
        'Activities',
        [
            {
                "event_name_here": {time: "7:30AM"}
            },
            {
                "event_name_here": {time: "7:30AM"}
            },
        ]
    ],
    [
         'Events',
        [
            {
                "event_name_here": {time: "7:30AM"}
            },
            {
                "event_name_here": {time: "7:30AM"}
            },
        ]
    ],
]);

```

```
in the component file:
return(
    <>
        {Object.keys(Schedule).map(() => {
            return(
                <>
                    <div>
                       your rectangles go here :)
                    </div>
                </>
            )
        })}
    </>
)
```

2022-08-01 05:51 UTC, andreidimaano requested changes
- see my comments about refactoring

Some answers:

>  I'm not sure how to make the columns (Events/Workshops/Activities) as wide as they appear on the CutieHack page.

There are many ways to do this, I would probably use a css grid on the wrapper. You can also use flex if you want to.

> I don't know how to make the descriptor text for each schedule item fit on a single line rather than continuing onto another line.

You don't need to do this, the text should wrap

2022-08-01 06:30 UTC, minsooerickim commented
#10

2022-08-01 15:53 UTC, nibchao commented
> Can you upload a screenshot of what it looks like

![unknown](https://user-images.githubusercontent.com/57279548/182189385-7d923442-0801-4044-843d-bd8d2e24678e.png)

this is how it looks at the moment before making any changes to my code

2022-08-08 23:37 UTC, minsooerickim commented on .gitignore
> +.gitignore
don't put .lock files in .gitignore. Also we shouldn't have `package-lock.json`

2022-08-08 23:38 UTC, minsooerickim commented
@nibchao for future reference, reply to the comments made by the reviewers so they know you've pushed up changes and they can review again

2022-08-08 23:50 UTC, nibchao commented
@minsooerickim sorry, i'm not familiar with pull requests and didn't know my commits would show up and/or notify participants(?), so i always committed/pushed immediately even with code that doesn't work. is it correct to continually make commits on vs code until i have working code then do a single push when it's ready for review?

2022-08-09 00:02 UTC, minsooerickim commented
> correct to continually make commits on vs code until i have working code then do

no need to apologize ahah. I don't think there is a set rule you need to follow but this is the general workflow I follow

1. make changes on vscode
2. commit as much as I can with useful commit messages
3. then once a section of a code is working (the whole thing doesn't have to be ready) or I decide I want to stop working for the day, I push it up to github even if it has broken code
4. then once I think the code is ready for review (my code addresses the issue), I open a pull request so people can review my code

After the pull request is open and people make comments, the changes are usually small so I address most of the changes in one or two commits then push it up. Once the PR (pull request) is open, I generally don't push up broken code. 

Workflow is something you learn as you go so don't be afraid to make mistakes!! and let me know if you have any other questions

2022-08-09 04:07 UTC, andreidimaano requested changes
Great job creating the map! :) It's a pretty tough concept to learn but it's a really important pattern that all frontend developers need

There are some bugs and design issues, please let me know if you need help fixing them.

when you're done please send a screenshot of what you rendered :)

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/Schedule.tsx
> +            {/* <div className="flex flex-col w-full gap-5">
you can delete this :) the refactor is good

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItem.tsx
> +    <>
unnecessary fragment tags <> </>

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItem.tsx
> +        {Object.keys(ScheduleItemArray).map((item, index) =>
move this up to the schedule class

```     
<div id="Schedule-Wrapper" className="flex flex-row gap-12 px-12 my-6"> 
    {Object.keys(ScheduleItemArray).map((scheduleItem) => {
        <ScheduleItem  scheduleItem={scheduleItem} />
    })}
  </div>
```

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItem.tsx
> +                      <div key={index} className="flex flex-col font-medium">{item}</div>
don't make keys indices, keys should be unique, i would use the `item` or if you're using my code, `scheduleItem`. whichever is the param name you're using

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItem.tsx
> +export const ScheduleItem = () =>
pass in the props(parameters in general terms) you need for each item like this:

`export const ScheduleItem = (props) => `

you can define the specific parameters like this:
`export const ScheduleItem = ({date, time, location}) => `
this is also known as destructuring
- [destructuring](https://medium.com/@lcriswell/destructuring-props-in-react-b1c295005ce0)
- [react docs](https://reactjs.org/docs/components-and-props.html)

then when you use this component in your Schedule component, you pass it in like this:
`<ScheduleItem date={data_variable_here} time={time_variable_here} location={location_variable_here}/>`

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItem.tsx
> +                          time
get this from the param value (see above)

if you are using `const ScheduleItem = (props) => {}`, then you want to do this:
```
<div className="flex flex-col w-full text-left font-medium">
    {props.time}
</div>
```
the `{}` signal javascript to use the variable name inside instead of a string literal

if you are using `const ScheduleItem = ({date, time, location}) => {}`, then you want to do this:
```
<div className="flex flex-col w-full text-left font-medium">
    {time}
</div>
```

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItem.tsx
> +                            <div>location</div>
don't need a `<div>`, just need location. make sure you use the variable name you pass as a parameter

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItemArray.jsx
> +                {
in terms of code readability, it's difficult to read code when brackets are formatted like this. Instead do this:

```
"Check-In": {
    date: "Saturday, April 2", 
    time: "7 - 8 AM", 
    location: "Hybrid (In-Person @ MSE 116)"
},

```

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItemArray.jsx
> +export const ScheduleItemArray = new Map
rename this to`ScheduleItemMap`

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItemArray.jsx
> +([
bracket styling:

`export const ScheduleItemArray = new Map ([`

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItemArray.jsx
> +        "Events",
bracket styling:

```
["Events", [
    {},
    {},
 ]],
```

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/ScheduleItemArray.jsx
> +            {
I think the design of this data structure needs to change,

overall, we're using a map, which is really nice. Maps have a [key: value] pair.

our keys are: ["Events", "Workshops", "Activities"]
Each key needs to map to an array of descriptions.
Each description will have the following properties:
```
type Description = {
    eventName: string
    date: string
    time: string
    location: string
}
```
so overall we have this:
```
Map([
    ["Events": [
        {
            eventName: "EventName here"
            date: "date here",
            time: "time here",
            location: "location here",
        },
        {
            eventName: "EventName here"
            date: "date here",
            time: "time here",
            location: "location here",
        },
    ]],
    ["Workshops", [
        {
            eventName: "EventName here"
            date: "date here",
            time: "time here",
            location: "location here",
        },
        {
            eventName: "EventName here"
            date: "date here",
            time: "time here",
            location: "location here",
        },
    ]],
])
```

2022-08-09 04:07 UTC, andreidimaano commented on components/Schedule/Schedule.tsx
> +        <ScheduleItem></ScheduleItem>
When you recode the map, you'll do something like this:

```
<div id="Schedule-Wrapper" className="flex flex-row gap-12 px-12 my-6"> 
  {ScheduleItemMap.get("Events").map((scheduleItemDescription) => {
    return (
      <ScheduleItem 
        name={scheduleItemDescription.name} 
        date={scheduleItemDescription.date} 
        time={scheduleItemDescription.time} 
        location={scheduleItemDescription.location}
      />
    )
  })} 
{ScheduleItemMap.get("Workshop").map((scheduleItemDescription) => {
    return (
      <ScheduleItem 
        name={scheduleItemDescription.name} 
        date={scheduleItemDescription.date} 
        time={scheduleItemDescription.time} 
        location={scheduleItemDescription.location}
      />
    )
  })} 
 // add the last one here!!
</div>
```

2022-08-09 04:08 UTC, andreidimaano commented
> @minsooerickim sorry, i'm not familiar with pull requests and didn't know my commits would show up and/or notify participants(?), so i always committed/pushed immediately even with code that doesn't work. is it correct to continually make commits on vs code until i have working code then do a single push when it's ready for review?

do a lot of commits and then make one PR, if you're code doesn't work and you are having issues unblocking yourself, ask in the discord channel and I can help :D

2022-08-13 00:16 UTC, nibchao commented
![unknown](https://user-images.githubusercontent.com/57279548/184459117-42454f70-89eb-47a7-8578-e2443dfc434c.png)
here's a new screenshot of how the schedule page looks after all the changes. thank you andrei for breaking down all the changes that needed to be made and minsoo for explaining workflow for pr's!

2022-08-13 20:30 UTC, andreidimaano approved these changes

2022-09-02 03:23 UTC, minsooerickim commented
remove ur yarn.lock file, idk where u got those changes but it doesn't look like ur using any new packages

2022-09-02 03:23 UTC, minsooerickim commented on components/Schedule/Schedule.tsx
> +          </div> */}
if this is unused code, remove it

2022-09-02 03:24 UTC, minsooerickim commented on components/Schedule/ScheduleItem.tsx
> +    <>
y is this here?

2022-09-02 03:25 UTC, minsooerickim commented on components/Schedule/ScheduleItemMap.jsx
> +export const ScheduleItemMap = new Map([
y we usin .jsx instead of tsx? 

and what is this Map function, y don't u just use do scheduleitemMap = {...}

2022-09-02 03:26 UTC, minsooerickim commented on components/Schedule/ScheduleItem.tsx
> +          <div className="italic text-sm font-normal">
do we need all these divs, it seems a bit extraneous

2022-09-02 03:28 UTC, minsooerickim commented on components/Schedule/Schedule.tsx
> +import { Page } from '@/components/Page/Page'
can u abstract all the mapping and details out to another file, i would ideally just want components to be rendered here

2022-09-02 03:29 UTC, minsooerickim commented
nice work btw, sry if my comments sound a bit harsh; I'm not trying to be mean lol it just takes too much time to write out nice sentences

2022-09-12 03:50 UTC, minsooerickim commented
for yarn.lock, you can just delete the file and push up the deleted change, no need to copy paste anything. Once you do that, you should see no yarn.lock file under 'changes' tab on github

2022-09-12 03:54 UTC, minsooerickim commented
make sure you @ whoever left comments after u address their comments, so they can come check ur updated changes, then they can resolve their threads :)

2022-09-14 01:10 UTC, nibchao commented
@minsooerickim did i address all of your comments with the changes/commits i've done? i deleted yarn.lock in both my schedule-section and support-section branches, but it seems deleting it for only schedule-section branch causes issues? 
![image](https://user-images.githubusercontent.com/57279548/190036306-a97bb359-0cf2-4090-9b8c-124742e83686.png)

2022-09-23 00:36 UTC, minsooerickim commented
> @minsooerickim did i address all of your comments with the changes/commits i've done? i deleted yarn.lock in both my schedule-section and support-section branches, but it seems deleting it for only schedule-section branch causes issues? ![image](https://user-images.githubusercontent.com/57279548/190036306-a97bb359-0cf2-4090-9b8c-124742e83686.png)

same comment as my latest comment [here](https://github.com/citrushack/cutiehack2022/pull/61). just don't commit the deleted yarn.lock changes

2022-09-26 03:26 UTC, nibchao commented
@minsooerickim i did the same thing with the yarn.lock file in this branch as i did in the support section branch and now the deleted LOC is this instead of the -3k it was earlier
![image](https://user-images.githubusercontent.com/57279548/192188014-dee9e2bf-d8c8-4981-8cdf-438f5712b837.png)

2022-10-24 23:28 UTC, closed without merging